baseURL = '/'
languageCode = 'en-us'
title = 'Saif workplace'
theme = "hugo-PaperMod"
disableInlineShortcodes = false
enableRobotsTXT = true
enableEmoji = true
enableMissingTranslationPlaceholders = false
enableGitInfo = true
useChroma = true
useKaTeX = true
useScss = true
useJsBundle = true
useFingerprint = false
useMinified = false
useHugoDeps = false
useCloudinary = false